import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header/header";
import Footer from "./footer/footer";
import Providers from "./providers";
import authenticated from "./auth/authenticated";
import logout from "./auth/logout";
import { Box, CssBaseline } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const isAuthenticated = await authenticated();

  return (
    <html lang="fr">
      <body
        className={inter.className}
        style={{
          margin: 0,
          padding: 0,
          display: "flex",
          flexDirection: "column",
          minHeight: "100vh", // ✅ Assure que tout prend bien la hauteur complète
        }}
      >
        <Providers authenticated={isAuthenticated}>
          <CssBaseline />
          <Header logout={logout} />

          {/* ✅ Le container principal grandit pour pousser le footer en bas */}
          <Box
            sx={{
              flex: "1", // ✅ Permet au contenu de prendre toute la place dispo
              width: "100%",
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              paddingTop: "64px", // ✅ Pour éviter que le contenu touche le header
            }}
          >
            {children}
          </Box>

          <Footer /> 
        </Providers>
      </body>
    </html>
  );
}
