name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  test_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Node.js et les dépendances
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install

      - name: Exécuter les tests unitaires
        run: npm test || echo "Aucun test pour l'instant, mais la pipeline fonctionne 😉"

      - name: Construire l’image Docker
        run: docker build -t mon-backend .
